name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to server
      run: |
        rsync -av --delete $GITHUB_WORKSPACE/ /var/alphadevs/my_web_app/CloudTestFrontend/
        cd /var/alphadevs/my_web_app/CloudTestFrontend
        npm ci
        npm run build

    - name: Restart app
      run: pm2 restart CloudTestFrontend || pm2 serve /var/alphadevs/my_web_app/CloudTestFrontend/build 3000 --name CloudTestFrontend --spa