name: Frontend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 3. Deploy source to server
      - name: Deploy source to server
        run: |
          rsync -av --delete \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.github \
            $GITHUB_WORKSPACE/ /var/alphadevs/my_web_app/CloudTestFrontend/

      # 4. Create .env file 
      - name: Create environment file
        run: |
          cd /var/alphadevs/my_web_app/CloudTestFrontend

          cat <<EOF > .env
          REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
          EOF

      # 5. Install dependencies
      - name: Install dependencies
        run: |
          cd /var/alphadevs/my_web_app/CloudTestFrontend
          npm install

      # 6. Build React app (env injected here)
      - name: Build app
        run: |
          cd /var/alphadevs/my_web_app/CloudTestFrontend
          CI=false npm run build

      # 7. Restart PM2 safely
      - name: Restart app
        run: |
          pm2 delete CloudTestFrontend || true
          pm2 serve /var/alphadevs/my_web_app/CloudTestFrontend/build 3000 --name CloudTestFrontend --spa